name: RDP_DITZZ_FINAL_BANTAI
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 1. Setup RDP Kasta Sultan
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin Ditzz77!

    - name: 2. Pasang Ngrok (Jalur Cepat)
      run: |
        curl -L --output ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
        tar -xf ngrok.zip

    - name: 3. EKSEKUSI & AMBIL LINK
      run: |
        Write-Host "Menyiapkan Terowongan Ngrok... Sabar Tuan Han!"
        Start-Process .\ngrok.exe -ArgumentList "tcp --region ap 3389"
        Start-Sleep -s 20
        $log = curl.exe -s http://127.0.0.1:4040/api/tunnels
        $obj = $log | ConvertFrom-Json
        $url = $obj.tunnels.public_url
        $cleanUrl = $url.Replace("tcp://", "")
        Write-Host "`n=========================================="
        Write-Host "ALAMAT PC: $cleanUrl"
        Write-Host "USER: runneradmin"
        Write-Host "PASS: Ditzz77!"
        Write-Host "=========================================="
        $i = 0; while($i -lt 360){Write-Host "RDP ON - $(Get-Date)"; Start-Sleep -s 60; $i++}
        
