name: RDP_UNLIMITED_HAN
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Membuka Gerbang RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        $Password = ConvertTo-SecureString "Ditzz77!" -AsPlainText -Force
        New-LocalUser -Name "ditzz" -Password $Password -FullName "Ditzz Modder" -Description "RDP User"
        Add-LocalGroupMember -Group "Administrators" -Member "ditzz"
    - name: Memasang Ngrok Otomatis
      run: |
        choco install ngrok
    - name: Menghubungkan Mesin
      run: |
        ngrok authtoken ${{ secrets.TOKEN_NGROK_TUAN }}
        ngrok tcp 3389
        
